### PR TITLE
add possible legend markers for scatter plot Viz

### PR DESCRIPTION
**Pull request by moontrip**
made possible legend markers for scatter plot Viz. More detailed adjustments (size etc.) are probably required when adding the custom legend to the Scatter plot with faceted plot.

### CODE REVIEW

**Comment by bobular** [comment]
Hi @moontrip  - could you post a screenshot please?

I'm not seeing any new marker this when using EDA `main` branch
image
(LLINEUP Cluster Randomized Trial)

Same when using faceting (e.g. "Region")

Or are you waiting for me to merge scatter wiring?  That's done now!

**Comment by bobular** [comment]
Aha, I see there is a bit more "wiring" to do here on the EDA side. If you're not working on this today, I can have a go tonight.

**Comment by moontrip** [comment]
@bobular yes it needs to be done at web-eda's scatterplot for wiring - I just made marker shapes in this PR. Thank you for your kind consideration 👍 but I will try to address it today - it is a bit tricky though

**Comment by moontrip** [comment]
@bobular now updated for scatter plot Viz

**Review by jtlong3rd — APPROVED** [review]

**Review by bobular — APPROVED** [review]
Hope you don't mind my minor tweaks!

**Pull request merged**
