### PR TITLE
Upgrade typescript to 4.3.4

### PR DESCRIPTION
**Pull request by bobular**
Motivation was some trouble with [map](https://stackoverflow.com/questions/58772314/typescript-array-prototype-map-has-error-expression-is-not-callable-when-th), and being substantially behind the TS version used in web-eda. They are the same now.

Required a storybook upgrade too.

One warning from Storybook UI/console says

```
warn: (1) ["\`argType.defaultValue\` is deprecated and will be removed in Storybook 7.0.
```
I can't see where we are doing this, but YMMV by reading the [change logs](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-argtype-defaultValue)

### CODE REVIEW

**Comment by jtlong3rd** [comment]
Thanks for doing this, @bobular! FYI - you'll probably want to run `npx sb upgrade` to make sure all appropriate `@storybook` packages get upgraded. 

https://github.com/styleguidist/react-docgen-typescript/issues/356#issuecomment-874607167

**Comment by bobular** [comment]
OK, so I just spent over an hour trying to figure out the following issue:

This branch and all the stories seem to work fine.

But if you revert to the `main` branch - the storybook gets stuck in a loop attempting hot module replacement because a request for
http://localhost:46835/15e7324d20ecd7dd73e7.hot-update.json (for example) is not found.  

I thought maybe it was my emacs IDE compiling in the background but I stopped that and still get the problem.
Switching back to this branch - it is stable/working.
Switch back to `main` and it's stuck in a loop again.

It could be something specific with my machine.  If I could find webpack temporary files/cache (if they exist) and remove them, I would.  I'll try a `git checkout main; yarn cache clean; yarn ; yarn storybook` just for kicks...  

No, that still gets stuck in a loop.

Are we going to break something if we merge this branch?  Seems like there may be no going back to older TS/SB versions.

**Comment by moontrip** [comment]
@bobular My two cents:
I am not so clear what a loop means but anyway I tried to use this branch at my test web-component: I have multiple web-component at my local VM haha. Anyway, tried yarn install at this branch and it went well. Go back to main branch, git pull, make a new branch from main, merged this typescript branch to the new branch, and run storybook. It seems to work fine as well.

As for going back to old version(s), it means we need to reset the commit and technically possible by combining git reset & push (or even git revert may work). Then, one can just delete node_module directory and reinstall package with older package.json that points out older TS/SB versions.

**Comment by bobular** [comment]
I'm glad the git checkout back to `main` worked for you @moontrip 
I guess this means there is something idiosyncratic (!) with my computer (though it is my Ubuntu box, not the Windows laptop I sometimes use).

I hope we go ahead with the upgrade.  I have a new [branch](https://github.com/VEuPathDB/web-components/tree/boxplot-empty-boxes-ts4.3.4) using it - where I have sorted the boxplot problems (related to fixed-ordered categorical axes, and missing data for some category values).

**Comment by moontrip** [comment]
> I'm glad the git checkout back to `main` worked for you @moontrip
> I guess this means there is something idiosyncratic (!) with my computer (though it is my Ubuntu box, not the Windows laptop I sometimes use).
> 
> I hope we go ahead with the upgrade. I have a new [branch](https://github.com/VEuPathDB/web-components/tree/boxplot-empty-boxes-ts4.3.4) using it - where I have sorted the boxplot problems (related to fixed-ordered categorical axes, and missing data for some category values).

idiosyncraises ! 😄 I am also using ubuntu VM under Windows haha. Perhaps you can try to do git clone web-component at other directory and see if it would work for you as well? :)

**Review by jtlong3rd — APPROVED** [review]

**Comment by bobular** [comment]
Made this a draft PR because #174 has the TS upgrade too.

**Pull request merged**
