### PR TITLE
Map and CSS tweaks to enable use in EDA

### PR DESCRIPTION
**Pull request by bobular**
Progress so far
- commented out the problematic CSS imports.  Need a better solution please anyone!
- named the handlers for bounds (top/bottom/left/right) and viewports (center lat/lon and zoom level) more consistently

### CODE REVIEW

**Comment by bobular** [comment]
In the latest commit I moved the most important/functional CSS file into /dist and I think I've set up package.json so that npm will package this.  It seems to work in EDA via yarn link but I am hopeful also for npm...

It seems that these styles have to be handled through static CSS files because the classes are added/removed directly to DOM elements, not React components, though I could be wrong.

**Comment by bobular** [comment]
Dear reviewer... thank you for looking at this PR.
The big question is... will the `dist` packaging of CSS work in npm?
Note that there is a bunch of CSS in `public` still (vb-popbio-maps.css) - this does not get seen by EDA and I don't think anything there is critical for the map component.  We can let vb-popbio-maps.css atrophy or perhaps delete it (or remove it from the storybook header includes?)

**Comment by dmfalke** [comment]
> Dear reviewer... thank you for looking at this PR. The big question is... will the `dist` packaging of CSS work in npm? Note that there is a bunch of CSS in `public` still (vb-popbio-maps.css) - this does not get seen by EDA and I don't think anything there is critical for the map component. We can let vb-popbio-maps.css atrophy or perhaps delete it (or remove it from the storybook header includes?)

If the css files are included in the output folder and included with the npm package, things should work as expected. It is the responsibility of the consumer package to process CSS imports. We do that via webpack in both web-eda and our websites.

**Review by dmfalke — APPROVED** [review]

**Comment by chowington** [comment]
@bobular I tested the map on storybook, and when you attempt to zoom in/out, it bounces back to the original zoom level. Seems to work on wed-eda though!

**Comment by bobular** [comment]
> @bobular I tested the map on storybook, and when you attempt to zoom in/out, it bounces back to the original zoom level. Seems to work on wed-eda though!

Ooh, thank you.  I was very bad and didn't test the storybook. Will investigate now.

**Comment by bobular** [comment]
Fixed the stories issue found by Connor.

Going to merge this now and test the CSS stuff via npm

**Comment by bobular** [comment]
Seems to work after yarn unlinking and using npm :-)

**Pull request merged**
