### PR TITLE
add a default prop, fixedrange, at PlotlyPlot

### PR DESCRIPTION
**Pull request by moontrip**
this will address the issue at web-eda, [All visualization plots need static axes (undraggable/unscrollable)](https://github.com/VEuPathDB/web-eda/issues/143)

### CODE REVIEW

**Comment by bobular** [comment]
Looks good. Does it matter if a plot doesn't have an x-axis or y-axis? (does PiePlot complain?)

**Comment by moontrip** [comment]
> Looks good. Does it matter if a plot doesn't have an x-axis or y-axis? (does PiePlot complain?)

@bobular I tried to use pieplot/donut stories and it seems to be fine without complaints :)

**Review by bobular — CHANGES_REQUESTED** [review]
I basically approve, but please remove the `fixedrange: true` from Histogram.tsx first.

Also let's discuss tomorrow if we really never want to have Plotly's dynamic axes (e.g. in a non-EDA setting).

**Comment by moontrip** [comment]
@bobular I just removed the fixedrange options from histogram component

**Review by jtlong3rd — APPROVED** [review]

**Review by bobular — APPROVED** [review]

**Review by dmfalke — APPROVED** [review]

**Pull request merged**
