### PR TITLE
implementing Barplot component with storybook controls

### PR DESCRIPTION
**Pull request by moontrip**
implemented Barplot component. Also storybook controls were added.
This will be used with barplot viz at web-eda

### CODE REVIEW

**Comment by moontrip** [comment]
tested empty data case and it works by sending empty array of object at data props

**Review by bobular — APPROVED** [review]
Nice job. I especially appreciated the storybook controls story.

I made some small adjustments to the empty plot appearance, and added a y axis black line to match the one discussed in the meeting yesterday for Histogram.

**Comment by moontrip** [comment]
Thanks @bobular for your review and changes you have made 👍 
Do I have to wait for Dave and Jamie for their approvals before merge ? IDK whether we need all reviewers' approvals for merge or one of them is sufficient

**Review by dmfalke — APPROVED** [review]

**Review by jtlong3rd — APPROVED** [review]

**Comment by moontrip** [comment]
Thank you for reviewing this PR, @bobular, @dmfalke, and @jtlong3rd. Although this is approved, I have made [one additional commit](url) concerning axis tick labels to show and hide, which will be used in viz's grid view/thumbnail. It is relatively simple but I am not quite sure if you want to review it again. I will wait for some time anyway :)

**Review by dmfalke — COMMENTED** [review]
Thanks @moontrip, I think this is a nice feature to add. Something strange happens when toggling the value of either of these new props in the controls for the story. It looks like a glitch in the Plotly library. The y-axis shifts up a unit, causing the bars to begin at -1. See the attached screenshot.

image

**Comment by moontrip** [comment]
> Thanks @moontrip, I think this is a nice feature to add. Something strange happens when toggling the value of either of these new props in the controls for the story. It looks like a glitch in the Plotly library. The y-axis shifts up a unit, causing the bars to begin at -1. See the attached screenshot.
> 
> image

Thank you for your review @dmfalke  👍  yes I also noticed it through playing with plot control, and somehow it could be corrected whenever using other control, e.g., staticPlot boolean. Since it worked fine via props (not via plot control) as shown in the corresponding viz PR with a screenshot, I didn't look into it carefully. It may be plotly issue as you guessed.

**Review by dmfalke — APPROVED** [review]
I'm fine with ignoring that glitch for now. We can revisit if it appears in a real world scenario.

**Review by jtlong3rd — APPROVED** [review]

**Review by bobular — APPROVED** [review]
Looks great - thanks DK - sorry for the delay

**Pull request merged**
