### PR TITLE
Improve handling of date variables in blue selection range of histograms

### PR DESCRIPTION
**Pull request by jernestmyers**
Addresses issue #322.

### CODE REVIEW

**Comment by jernestmyers** [comment]
@bobular I'm curious what you think about this approach. I used Chrome's dev tools to play with time zones and didn't notice any issues thus far.

It seems like `range.max` already has the date format necessary for `rightCoordinate` since my previous change uses the last bin's `binEnd` as the limit irrespective of format.

**Review by bobular — COMMENTED** [review]
Hi! When I am "zoomed" in to day resolution (GEMS1 "observation date"), the right-most bin is "snapping" properly, but the others only select/go blue if you drag past the half-way point of the bin/bar to the right of the one you are selecting. So to select one day, you have to drag over two bars.

In week-resolution mode, the snapping is behaving fine, but the blue rectangle isn't wide enough.

Looks like some more testing/discussion may be required - we could meet for this?

(Just checking, there is no `web-eda` PR that goes with this?)

**Comment by jernestmyers** [comment]
@bobular I apologize for not pushing my most up-to-date changes until this morning. As a result, I'm not sure if you tested the most recent code and read those comments. Either way, that behavior you described remains and it is due to how we subtract 1 day from the selector. I am not sure why it was ever necessary, but I feel that removing that adjustment will dramatically simplify my approach.

**Comment by bobular** [comment]
I think the problem is that `DateMath.endOf()` is calculating the end of the day in the browser's local time zone (for the date in question, so the May 2011 observation dates are in BST (GMT+1) for me)

e.g. Sun May 08 2011 23:59:59 GMT+0100 (British Summer Time)

When converted back to ISO string it becomes 2011-05-08T22:59:59.999Z

I don't see an obvious solution, other than to add on the offset, which you can get from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset

**Comment by bobular** [comment]
Or (if non-integers allowed, which I assume they are) add 0.9999999 days.

**Comment by jernestmyers** [comment]
While testing with multiple timezones, I noticed that those with `timezoneOffsets > 0` were behaving as I would have expected. But those with negative `timezoneOffsets` were jumping ahead a day during selection. I am not entirely sure as to why that happens, but subtracting an extra day's worth of minutes seemed to solve the problem.

**Review by bobular — APPROVED** [review]
Works well for me in BST-land!

**Pull request merged**
