### PR TITLE
addressing SVG log scale

### PR DESCRIPTION
**Pull request by moontrip**
This draft PR is branched out from https://github.com/VEuPathDB/web-components/pull/371 as this needs map's log scale functionality

This is a temporary solution, just minimizing gap between small and large (using mouse tool) charts: Please see this comment for more detailed info: https://github.com/VEuPathDB/web-components/issues/380#issuecomment-1203128901.

### CODE REVIEW

**Comment by moontrip** [comment]
updated as noted at https://github.com/VEuPathDB/web-components/issues/380#issuecomment-1205613883

**Comment by moontrip** [comment]
@bobular it would be great if you can test this PR when you will be available

**Review by bobular — APPROVED** [review]
This is looking and working great.

I only have one optional suggestion: the localMin and localMax values are calculated even if they are not needed. I know it's not very expensive, but you know me! Perhaps it could be calculated conditionally, something like

```
  const yAxisRange = props.dependentAxisRange
    ? props.dependentAxisRange
    : { min: Math.min(...), max: Math.max(...) };
```
(probably with a `as NumberRange` ;-) )

and use yAxisRange in the calculations of barHeight (which also simplifies the code there, I think)

**Comment by moontrip** [comment]
@bobular I have addressed your suggestions by introducing localMinMaxPosRange that includes min/max computation conditionally. 👍

**Comment by moontrip** [comment]
@bobular I have changed this PR with the discussions we had. It looks fine for me but it would be great if you can test this too 👍

**Comment by bobular** [comment]
> @bobular I have changed this PR with the discussions we had. It looks fine for me but it would be great if you can test this too +1

Hi @moontrip - I haven't tested it but I looked at the code carefully and it gets the :+1:  from me!

**Comment by moontrip** [comment]
Thank you for your review, @bobular 👍

**Pull request merged**
