### PR TITLE
changing legend styles

### PR DESCRIPTION
**Pull request by moontrip**
This will address https://github.com/VEuPathDB/web-components/issues/344

Done based on several comments by Bob and Dave in the ticket
- [x] set legend width to be 400px like other tables (plz see below screenshot)
- [x] introduced `text-overflow: ellipsis` instead of a functional approach: removed the function, `legendEllipsis` 
- [x] set bold for legend title to distinguish from legend labels
- [x] made some left and bottom margins for better display

For reference, a screenshot is attached in the following:
legend-size-adjust1

### CODE REVIEW

**Comment by moontrip** [comment]
made another screenshot to be compared with the previous example in the ticket

- before (taken from the ticket)
163481335-f2876a6b-3f9a-42cf-9a7b-552082d3f8bd

- after (this PR)
histogram-legend1

**Review by bobular — APPROVED** [review]
All looks great. Confirm the ellipsis mouse-overs are working fine for the legend values.

I couldn't find a variable name long enough to test the legend title, but it's possible that this also needs `textOverflow: ellipsis` ?

**Comment by bobular** [comment]
> All looks great. Confirm the ellipsis mouse-overs are working fine for the legend values.
> 
> I couldn't find a variable name long enough to test the legend title, but it's possible that this also needs `textOverflow: ellipsis` ?

Ah, I found one - the title is wrapped, which I think is the better solution!

image

**Comment by moontrip** [comment]
> 

Thank you for your review and tests, @bobular 👍 Actually I didn't think of ellipsis on the legend title as it is quite rare to see very long title, especially with the increased width and wrapping. Glad you like the wrapped title 😃

**Pull request merged**
