### PR TITLE
Cosmetic fixes to histogram and scatterplot controls

### PR DESCRIPTION
**Pull request by bobular**
Removed the border and title for the histogram, made the scatterplot controls look like the histogram ones

### CODE REVIEW

**Comment by moontrip** [comment]
@bobular I tried to see the outcome of your change for XYPlotControls and it is like the following. Is this what you want? 

scatterControls

I have to set marginTop: '1em' to capture the screen appropriately as the box without that margin start from top right corner of screen: the text Plot options are hidden in half but maybe fine for its use at viz? Perhaps we need some margin in there?

**Comment by bobular** [comment]
> @bobular I tried to see the outcome of your change for XYPlotControls and it is like the following. Is this what you want?
> 
> scatterControls
> 
> I have to set marginTop: '1em' to capture the screen appropriately as the box without that margin start from top right corner of screen: the text Plot options are hidden in half but maybe fine for its use at viz? Perhaps we need some margin in there?

Hi DK - I'm going to change the histogram controls to look more like your scatterplot controls (more modern/clean).

**Comment by bobular** [comment]
Now looks like DK's

image

**Review by jtlong3rd — APPROVED** [review]

**Comment by moontrip** [comment]
@bobular I have done some limited tests  and it looks good and works fine

**Review by moontrip — APPROVED** [review]

**Pull request merged**
